# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for DevOps Agent Dashboard (macOS)."""
import os

block_cipher = None

DASHBOARD_DIR = os.path.abspath(os.path.join(SPECPATH, ".."))
REPO_ROOT = os.path.abspath(os.path.join(DASHBOARD_DIR, "..", ".."))

a = Analysis(
    [os.path.join(SPECPATH, "launcher.py")],
    pathex=[DASHBOARD_DIR, REPO_ROOT],
    binaries=[],
    datas=[
        (os.path.join(SPECPATH, "flask_server.py"), "desktop"),
        (os.path.join(DASHBOARD_DIR, "templates"), "templates"),
        (os.path.join(DASHBOARD_DIR, "static"), "static"),
        (os.path.join(DASHBOARD_DIR, "config.yaml.example"), "."),
        (os.path.join(DASHBOARD_DIR, "arch_questions.json"), "."),
        (os.path.join(DASHBOARD_DIR, "prompts"), "prompts"),
        (os.path.join(DASHBOARD_DIR, "generation"), "generation"),
        (os.path.join(DASHBOARD_DIR, "providers"), "providers"),
        (os.path.join(DASHBOARD_DIR, "scenarios"), "scenarios"),
        (os.path.join(DASHBOARD_DIR, "dockercoins-scenarios"), "dockercoins-scenarios"),
        (os.path.join(REPO_ROOT, "simulator", "engine"), "simulator/engine"),
        (os.path.join(DASHBOARD_DIR, "expert_sidecar", "dist"), "expert_sidecar/dist"),
        (os.path.join(DASHBOARD_DIR, "expert_sidecar", "node_modules_prod"), "expert_sidecar/node_modules"),
        (os.path.join(DASHBOARD_DIR, "expert_sidecar", "package.json"), "expert_sidecar"),
        (os.path.join(SPECPATH, "node"), "node"),
    ],
    hiddenimports=[
        "flask",
        "flask_compress",
        "jinja2",
        "jinja2.ext",
        "yaml",
        "boto3",
        "botocore",
        "requests",
        "packaging",
        "packaging.version",
        # App modules
        "app_config",
        "config",
        "routes_setup",
        "routes_space",
        "routes_dag",
        "routes_arch",
        "routes_scenario",
        "routes_settings",
        "routes_security_targets",
        "routes_security_insights",
        "routes_skills",
        "routes_expert",
        "cluster_manager",
        "account_registry",
        "topology_provider",
        "credential_resolver",
        "execution_context",
        "verifier",
        "verifier_base",
        "verifier_checkers",
        "verifier_executors",
        "verifier_utils",
        "ai_provider",
        "arch_analysis",
        "arch_quality",
        "arch_worker",
        "chat_worker",
        "scenarios",
        "scenario_runner",
        "security_scenarios",
        "security_enrichment",
        "security_findings_store",
        "evaluator",
        "evidence",
        "error_response_strategy",
        "skill_manager",
        "readiness_probe",
        "alarm_provisioner",
        "validate_steps",
        "prompts",
        "generation",
        "generation.harness",
        "generation.types",
        "generation.submit_tool",
        "providers",
        "providers.agent_space",
        "providers.bedrock_direct",
        "providers.system_prompts",
        "providers.tool_executor",
        "providers.tools",
        "simulator",
        "simulator.engine",
        "simulator.engine.failure_modes",
        "simulator.engine.generator",
        "simulator.engine.state_collector",
        "simulator.engine.topology",
        "simulator.engine.enricher",
        "simulator.engine.recommender",
        "simulator.engine.chat_discovery",
        "simulator.engine.installer",
    ],
    hookspath=[],
    runtime_hooks=[os.path.join(SPECPATH, "runtime_hook.py")],
    excludes=["gunicorn", "tkinter", "pytest"],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="DevOpsAgent",
    debug=False,
    strip=False,
    upx=False,
    console=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name="DevOpsAgent",
)

app = BUNDLE(
    coll,
    name="DevOps Agent.app",
    bundle_identifier="com.devops-agent.dashboard",
    info_plist={
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion": "1",
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "12.0",
    },
)
